import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { connectToCoinbase } from '@/coinbase/connectCoinbase'
import { useEffect } from 'react'
import { coinbaseInit } from '@/coinbase/coinbaseInit'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(coinbaseInit,[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <button onClick={connectToCoinbase}>Connect</button>
        <button onClick={()=> window.open(`https://go.cb-w.com/dapp?cb_url=${window ? window.location.href : ''}`)}>Deeplink</button>
      </main>
    </>
  )
}
